#from graphing import FibonacciHeap
from algore.structures import LinkedList

ll = LinkedList()
ll.insert('a')
ll.insert('c')
ll.insert('b')
ll.insert('g')
ll.insert('w')
ll.insert('x')
ll.insert('i')
print(ll[2])
print(ll[0])
print(ll)
print(ll.reverse())
ll.pop(2)
print(ll)
print(ll.reverse())
ll.pop(0)
print(ll)
print(ll.reverse())
ll.pop(4)
print(ll)
print(ll.reverse())
#print(ll.root.value)
#print(ll.root.next.value)
#print(ll.root.prev.value)
#print(ll)
#fh = FibonacciHeap()
